#!/usr/bin/env python3
"""Generate the small compiled slave catalog from validated JSON input."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_u32(value: object, field: str) -> int:
    if not isinstance(value, str) or not value.startswith("0x"):
        raise ValueError(f"{field} must be a hexadecimal string")
    number = int(value, 16)
    if not 0 <= number <= 0xFFFFFFFF:
        raise ValueError(f"{field} is outside uint32 range")
    return number


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate(document: dict[str, object]) -> str:
    identity = document["identity"]
    pdo_sets = document["pdo_sets"]
    selected_id = document["selected_pdo_set"]
    if not isinstance(identity, dict) or not isinstance(pdo_sets, list):
        raise ValueError("identity and pdo_sets have invalid types")

    selected = next(
        (item for item in pdo_sets if isinstance(item, dict) and item.get("id") == selected_id),
        None,
    )
    if selected is None:
        raise ValueError(f"selected PDO set {selected_id!r} does not exist")

    rx = selected["rx"]
    tx = selected["tx"]
    conversion = document["conversion"]
    protocol = document["protocol"]
    if not all(isinstance(item, dict) for item in (rx, tx, conversion, protocol)):
        raise ValueError("profile contains an invalid object")

    values = {
        "profile_id": c_string(str(document["profile_id"])),
        "model": c_string(str(document["model"])),
        "vendor_id": parse_u32(identity["vendor_id"], "identity.vendor_id"),
        "product_code": parse_u32(identity["product_code"], "identity.product_code"),
        "revision": parse_u32(identity["revision"], "identity.revision"),
        "rx_index": parse_u32(rx["index"], "rx.index"),
        "tx_index": parse_u32(tx["index"], "tx.index"),
        "rx_bytes": int(rx["bytes"]),
        "tx_bytes": int(tx["bytes"]),
        "encoder_counts": int(conversion["encoder_counts_per_motor_revolution_default"]),
        "requires_dc": "true" if protocol["requires_distributed_clocks"] else "false",
    }

    return f"""/* Generated by tools/generate_slave_catalog.py. Do not edit. */
#include "emaster/slave_profile.h"

#include <stddef.h>

static const emaster_slave_profile_t profiles[] = {{
    {{
        .profile_id = {values['profile_id']},
        .model = {values['model']},
        .identity = {{
            .vendor_id = UINT32_C(0x{values['vendor_id']:08X}),
            .product_code = UINT32_C(0x{values['product_code']:08X}),
            .revision = UINT32_C(0x{values['revision']:08X}),
        }},
        .rx_pdo_index = UINT16_C(0x{values['rx_index']:04X}),
        .tx_pdo_index = UINT16_C(0x{values['tx_index']:04X}),
        .rx_pdo_bytes = UINT16_C({values['rx_bytes']}),
        .tx_pdo_bytes = UINT16_C({values['tx_bytes']}),
        .encoder_counts_per_motor_revolution_default = UINT32_C({values['encoder_counts']}),
        .requires_distributed_clocks = {values['requires_dc']},
    }},
}};

size_t emaster_slave_profile_count(void)
{{
    return sizeof(profiles) / sizeof(profiles[0]);
}}

const emaster_slave_profile_t *emaster_slave_profile_at(size_t index)
{{
    if (index >= emaster_slave_profile_count())
    {{
        return NULL;
    }}
    return &profiles[index];
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    document = json.loads(args.input.read_text(encoding="utf-8"))
    output = generate(document)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
